### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by vinaykashyap1996** [vinaykashyap1996/booking-system#6]
- [ ] check the view button on events 
- [x] add spinner instead of plain text
- [ ] set authorization for booking
- [ ] settings menu to show the user his profile
- [x] display error messages
- [ ] google login system 
- [ ] integrate stripe 
- [ ] build user profile
- [ ] improve design
